### ISSUE TITLE
MIME parts are represented as a tree, not a list.

### ISSUE THREAD

**Issue by skx** [lumail/lumail2#101]
We currently assume that the MIME parts included inside a message are a list, this is a bug.  Instead they should be a tree - with message-parts containing children as appropriate.

This replaces the previous issue - #79.

**Comment by jugglerchris** [comment]
This doesn't correctly handle nested multipart objects.
I have a message which is:

* multipart/mixed (parent is message)
  * multipart/related
    * multipart/alternative
      * text/plain
      * text/html
    * image/png
  * text/plain

but it comes out (as seen in Lua) as:
```
   type=multipart/mixed size=0 is_attachment=false filename=
      type=multipart/related size=0 is_attachment=false filename=
      type=text/plain size=140 is_attachment=false filename=
   type=multipart/related size=0 is_attachment=false filename=
      type=multipart/alternative size=0 is_attachment=false filename=
      type=image/png size=2516 is_attachment=true filename=Clip(12-23-17-55-26).
   type=multipart/alternative size=0 is_attachment=false filename=
      type=text/plain size=1948 is_attachment=false filename=
      type=text/html size=3545 is_attachment=false filename=
```
(indentation => nesting)

I'll probably have a play this evening.

**Comment by skx** [comment]
I'll be away for the next two nights so unable to look at it myself.

But if you do need help I think I'd probably want to see the message to see what is going on.  Also it would be worth clarifying if that nested-view is what you're seeing if you process the message yourself, or if you're seeing that output in the UI - because I don't (yet) handle recursion properly in attachment-mode (known issue.  I should report it).
