### ISSUE TITLE
Bright colours

### ISSUE THREAD

**Issue by jugglerchris** [lumail/lumail2#113]
Maybe I'm missing something, but I don't think there's a way to get the brighter colours.

eg $[YELLOW] gives a sort of browny colour on my terminal, but I'd quite like the bright/bold version to be available.  I guess it could either be $[BOLD]$[YELLOW] or $[BRIGHTYELLOW] etc.

**Comment by skx** [comment]
I guess you're really saying "We need colours AND attributes, not just colours".  If that is true we need to handle them all:

* DIM
* BOLD
* BLINK
* REVERSE
* STANDOUT
* UNDERLINE

I think I'd be happy with `$[YELLOW|BOLD]`, `$[GREEN|DIM]`, or `$[BLUE|BLINK]` if that would suit?  i.e. We'd always be `COLOUR` followed by an optional attribute `|ATTRIBUTE]`.

**Comment by skx** [comment]
I will assume this is closed unless I hear differently in the next few days :)

**Comment by jugglerchris** [comment]
Yes, sorry - I'm happy to close.  However, reading the notification e-mail for the above has reminded me that the colours need escaping when rendering the message.  :-)

**Comment by skx** [comment]
I guess report that as a new bug.

Similar thing happens if you *reply* to a message which has colours - I guess we need to trawl the git-history and reinstate `strip_colours` for that case.
