### ISSUE TITLE
Colour codes end up embedded in messages when replying

### ISSUE THREAD

**Issue by jugglerchris** [lumail/lumail2#122]
This could be solved by stripping them.

However, maybe it would be cleaner to change how colour rendering is done (eg return a list of {"RED", "message_text"} instead of inlining the codes), or just having a separate function to generate the quoted reply text than for rendering a message to screen.

**Comment by skx** [comment]
I wanted to avoid having a separate function because the formatting is complicated - picking the right part to render, etc - and repeating that would require making sure that future changes had to be kept in sync in multiple locations.

Still I'm open to suggestions / patches!

**Comment by skx** [comment]
I think this is simple to fix - if we just strip the colours pre-reply/pre-forward - but i've not looked in depth.

I will look once I've finished working on the initial IMAP support sometime next week.
