### ISSUE TITLE
Lua and Perl error messages are not readable

### ISSUE THREAD

**Issue by gber** [lumail/lumail2#139]
Lua and Perl error messages currently just go to stderr and are garbled while curses is in use. Opening my INBOX currently takes several minutes and then there is some Perl exception and lua errors which I unfortnunately can't read.

**Comment by skx** [comment]
Ugh.

You can try testing the access interactively to see if there is a sane error-message from Perl:

    export imap_username=login
    export imap_password=xxx
    export imap_server=imaps://mail.example.com/

    perl /etc/lumail2/perl.d/get-messages folder-name

**Comment by gber** [comment]
That takes a very long time (ca. 5min for 1500msgs) but works, so I guess the problem in the lua code?

**Comment by skx** [comment]
This is actually the C++ side.

I'll have to see if I can reproduce things here.

**Comment by skx** [comment]
I suspect,
[t.diff.txt](https://github.com/lumail/lumail2/files/99760/t.diff.txt)
 for the moment, the following patch might help you narrow down the error-message though:

**Comment by skx** [comment]
Also this one.

[t.diff.txt](https://github.com/lumail/lumail2/files/99765/t.diff.txt)

**Comment by gber** [comment]
Thanks, after a few attempts the latter sleep was enough to copy the error message, see issue #141

**Comment by skx** [comment]
Closing this as the `perl.d` files have been replaced with `perl.d/imap` - as per #140.
