### ISSUE TITLE
IMAP support?

### ISSUE THREAD

**Issue by RichiH** [lumail/lumail2#14]
New client, new game, old request:

IMAP support?

**Comment by skx** [comment]
In the past I said "No, never".

Right now I think "I don't need it".

Once the API changes have slowed down I'll make the message getting/handling a virtual interface and move the CMaildir stuff over to using it.  That will allow a brave soul to add support for IMAP/POP if they wish.

**Comment by RichiH** [comment]
Sounds good. Thanks :)

**Comment by skx** [comment]
I'm going to regard this as closed now, rather than continue to spam you with random updates.

There are some outstanding niggles, and setup is a little harder than I'd like, but as per the documentation in the file `IMAP.md` lumail can now perform operations over IMAP.

**Comment by RichiH** [comment]
Thanks :)

Richard

Sent by mobile; excuse my brevity.
