### ISSUE TITLE
Perl error while opening IMAP mailbox

### ISSUE THREAD

**Issue by gber** [lumail/lumail2#141]
With help from issue #139 I was able to capture the perl error when opening my IMAP INBOX:

    Can't use string ("34") as an ARRAY ref while "strict refs" in use at /usr/share/perl5/Net/IMAP/Client.pm line 431.

Calling `get-messages` via `perl /etc/lumail2/perl.d/get-messages INBOX` directly works fine.

**Comment by skx** [comment]
> Calling get-messages via perl /etc/lumail2/perl.d/get-messages INBOX directly works fine.

That makes this bug harder to deal with then.  If they don't fail the same way.

**Comment by skx** [comment]
Closing this as the `perl.d` files have been replaced with `perl.d/imap` - as per #140.
