### ISSUE TITLE
build fails because of src/uitl.h

### ISSUE THREAD

**Issue by fischerling** [lumail/lumail2#153]
gcc (6.1.1) fails with:

    In file included from src/util.cc:25:0:
    src/util.h:55:6: error: ‘vector’ in namespace ‘std’ does not name a template type
        std::vector<std::string> split(const std::string &text, char sep);
             ^~~~~~
    src/util.cc:32:6: error: ‘vector’ in namespace ‘std’ does not name a template type
        std::vector<std::string> split(const std::string &text, char sep)
             ^~~~~~

**Comment by skx** [comment]
Thanks for your contribution, I'm on Debian's jessie release with g++ 4.9.2 and don't need this, but it seems to be obviously correct.
