### ISSUE TITLE
Line wrapping is broken for the *last* line of the output.

### ISSUE THREAD

**Issue by skx** [lumail/lumail2#156]
If you're viewing a Maildir the which has a number of messages with long formatted index-entries then the last one will wrap.

**Comment by jugglerchris** [comment]
I don't think it's just the last one - if you have, say, 3 messages and the second one wraps over 3 lines, the last line will end up visible after the third message.

**Comment by skx** [comment]
I suspect you're right, @jugglerchris , but I hope the fix I've just pushed will resolve the problem whether the last line, or any other :)
