### ISSUE TITLE
When replying to a message don't insert the header.

### ISSUE THREAD

**Issue by skx** [lumail/lumail2#188]
A reply should look like this:

     > Blah ..
     > Blah

Not like this:

    > From: user@example.com
    > Date: ..
    > Subject: Meet hot devs in your area
    >
    > Blah blah, blah

**Comment by jugglerchris** [comment]
I'd argue it should look like this:

```
On <date>, User Name wrote:
> Blah ..
> Blah
```

:-)

**Comment by skx** [comment]
Happy to do that too :)
