### ISSUE TITLE
lumail2.lua uses variable defined in lumail2.user.lua without check

### ISSUE THREAD

**Issue by fischerling** [lumail/lumail2#204]
The function `select()` uses the global variable `folder_from`, which is defined
in lumail2.user.lua.

## Problem: 
I can't select a maildir with my own user config, that doesn't define
`folder_from`.

## Solution:
We should check if the variable is set and not assume that the user defines
it in the user config.

**Comment by fischerling** [comment]
## Alternative:

`folder_from` could also get stored in `Config`.
But maybe with a more explanatory name. At the first Glance I didn't really
understand what the purpose of the variable is.

**Comment by skx** [comment]
Good catch, thanks.

> At the first Glance I didn't really understand what the purpose of the variable is. 

I might be pushing my own preferences here, so I'll step back and think about it overnight.

But in short I have a bunch of domains.  Mail addressed to them typically goes into a distinct folder.  So mail sent to `*@steve.fi` goes to the folder `Maildir/steve.fi/`, and mail sent to `*@lumail.org` goes to the folder `Maildir/lumail.org/`.  The idea of that snippet of code is that if I open one of these folders I can set my outgoing mail address to the appropriate one ( steve@lumail.org, or steve@steve.fi, etc).

I suspect it actually makes more sense to drop this from the default config, and instead do something like this:

     function select()
        ...
        .. if the user has a hook function, invoke it
        ..
        if ( type( on_folder_selected ) == "function" ) then
              on_folder_selected( folder )
        end
        ..

That way I can move my logic there, and also provide a hook for user extension.

Does that explanation and plan seem reasonable?  I think it is probably an improvement, but I'll come back to it tomorrow.

**Comment by fischerling** [comment]
I really like the idea of using a hook.

It provides a lot of power and flexibility to the user.
Whole "Profiles" for different maildirs could be applied by the user.

**Comment by skx** [comment]
OK great, I'll close your pull request and go that way then :)
