### ISSUE TITLE
[osx] segfaulting with imap

### ISSUE THREAD

**Issue by xipmix** [lumail/lumail2#216]
$ lumail2 --version
     Lumail2 5ef9-dirty

I tested the IMAP connection stack from Net::IMAP::Client upward and I seem to be connecting ok. However as lumail is working through the initial folder scan and buidling up the cache, it segfaults after a few seconds. The failure occurs before it draws the normal startup screen.
Here's an example run. I'm running from my home dir, not the git checkout.

    $ lumail2 --debug
    Folder: google docs
                   lumail2(87938,0x7fff7a44d000) malloc: *** error for object 0x7fd748e22c40: incorrect checksum for freed object - object was probably modified after being freed.
                       *** set a breakpoint in malloc_error_break to debug
                                                                          Abort trap: 6

The lines from the log file:

    19/07/2016 22:46:14.113 CConfig variable changed maildir.prefix
    19/07/2016 22:46:14.114 CConfig variable changed maildir.max
    19/07/2016 22:46:14.115 CConfig variable changed global.mailer
    19/07/2016 22:46:14.116 CConfig variable changed global.editor
    19/07/2016 22:46:14.116 CConfig variable changed global.sender
    19/07/2016 22:46:14.116 CConfig variable changed colour.unread
    19/07/2016 22:46:14.116 CConfig variable changed global.history
    19/07/2016 22:46:14.116 CConfig variable changed message.cache
    19/07/2016 22:46:14.116 CConfig variable changed index.sort
    19/07/2016 22:46:14.116 CConfig variable changed imap.cache
    19/07/2016 22:46:14.116 CConfig variable changed index.sort
    19/07/2016 22:46:14.117 CConfig variable changed index.fast
    19/07/2016 22:46:14.117 CConfig variable changed imap.proxy
    19/07/2016 22:46:14.117 CConfig variable changed imap.server
    19/07/2016 22:46:14.117 CConfig variable changed imap.username
    19/07/2016 22:46:14.117 CConfig variable changed imap.password
    19/07/2016 22:46:17.346 CConfig variable changed maildir.max
    19/07/2016 22:46:17.346 Updating list of messages.
    19/07/2016 22:46:17.348 	IMAP is in use.
    19/07/2016 22:46:19.661 CConfig variable changed index.max
    19/07/2016 22:46:19.662 CConfig variable changed global.mode

So ... new platform, new malloc, new malloc quirks I guess.

As I try repeatedly, it seems to get further through the folder list before segfaulting again.
Apart from the obvious imap settings I have added this to my ~/lumail2/<host>.lua file

     --
     -- IMAP: Get the messages in the INBOX
     --
     local folders = Global:maildirs()
     
     -- For each one add the output
     for index,object in ipairs( folders ) do
        print( "Folder: " .. object:path() )
     
        --
        -- BUG: This doesn't reset the messages.
        --
        Global:select_maildir(object)
     
        --
        -- These two lines force a flush.
        --
        Config:set( "global.mode", "maildir" )
        Config:set( "global.mode", "index" )
     
        local messages = Global:current_messages()
     
        for k,v in pairs( messages ) do
           print( "\t" .. v:path() .. " " .. v:flags() .. " " .. v:header("subject") )
        end
     end
     
 Commenting tihis out removes the 'Folder: foo' part of the output but does not stop the segfaults.

Are there other debug knobs to turn on or is gdb the next step? Are there any simple tests of malloc that could be made to ensure it is behaving as expected?

I have not tested in 'Maildir' mode as yet.

**Comment by skx** [comment]
Thanks for the report, and I'm sorry this isn't working for you.

Unfortunately I have nothing too useful to add at the moment.  (If it does gets further on subsequent runs that does imply that the caching is masking a bug; such that when it is in-use it prevents the crash from earlier maildirs.)

As you suspect though `gdb` is probably the next step.  In the past I've spent a lot of time tracking down memory corruption and issues, and I thought I'd fixed all of them.  Looks like not though.

I'd be tempted to see if this is specific to IMAP though.  That might narrow the scope of the search, if nothing else..

**Comment by xipmix** [comment]
Trying maildir mode.
* comment out all things related to imap (config below)
*  I cloned some public test data from https://github.com/tcolar/mail302/tree/master/test/data/maildir and rsynced it into ~/Maildir.

lumail2 --debug starts up ok and says 'there are no visible folders'
The log is strange, lots of instances of 'changed maildir max' (147 if we're counting)

    20/07/2016 19:12:27.156 CConfig variable changed maildir.prefix
    20/07/2016 19:12:27.156 CConfig variable changed maildir.max
    20/07/2016 19:12:27.158 CConfig variable changed global.mailer
    20/07/2016 19:12:27.158 CConfig variable changed global.editor
    20/07/2016 19:12:27.158 CConfig variable changed global.sender
    20/07/2016 19:12:27.158 CConfig variable changed colour.unread
    20/07/2016 19:12:27.158 CConfig variable changed global.history
    20/07/2016 19:12:27.158 CConfig variable changed message.cache
    20/07/2016 19:12:27.158 CConfig variable changed index.sort
    20/07/2016 19:12:27.664 CConfig variable changed maildir.max

Config

    keymap['global']['^W'] = 'os.exit(1)'
    
    
    
    
    Config:set( "global.iconv", 1 )
    
    
    
    Config:set( "index.fast", 1 )
    
    local HOME = os.getenv("HOME")
    
    Config:set( "global.logfile", HOME .. "/lumail2.log" )
    
    Config:set( "maildir.prefix", HOME .. "/Maildir" );
    
    
    
    local def_save = HOME .. "/Maildir/sent-mail"
    if (Directory:is_maildir(def_save) ) then
       Config:set( "global.sent-mail", def_save)
    else
       Panel:append( "WARNING: No sent-mail folder defined!" )
    end
    
    
    if ( File:exists( "/usr/lib/sendmail" ) ) then
       Config:set( "global.mailer", "/usr/lib/sendmail -t" )
    elseif ( File:exists( "/usr/sbin/sendmail" ) ) then
       Config:set( "global.mailer", "/usr/sbin/sendmail -t" )
    else
       Panel:append( "WARNING: No sendmail binary found!" )
    end
    
    Config:set( "global.editor", "vim  +/^$ ++1 '+set tw=72'" )
    
    Config:set( "global.sender", "Some User <steve@example.com>" )
    
    Config:set( "colour.unread", "red" )
    
    Config:set( "global.history", HOME .. "/.lumail2.history" )
    
    Config:set( "message.cache", HOME .. "/.lumail2.cache" )
    cache:load( Config:get( "message.cache") )
    
    sorting_method( "file" )
    
    
    local folders = Global:maildirs()
    
    
    
    
    colour_table = {}
    
    for i,o in ipairs(Global:modes()) do
       colour_table[o] = {}
    end
    
    
    colour_table['maildir'] = {
       ['Automated'] = 'yellow|underline',
       ['lists']     = 'green|bold',
    }
    
    colour_table['index'] = {
       ['Steve'] = 'blue',
       ['Ian']   = 'blue',
    }
    
    colour_table['message'] = {
       -- headers
       ['^Subject:'] = 'yellow',
       ['^Date:']    = 'yellow',
       ['^From:']    = 'yellow',
       ['^To:']      = 'yellow',
       ['^Cc:']      = 'yellow',
       ['^Sent:']    = 'yellow',
    
       -- quoting, and nested quoting.
       ['^>%s*>%s*']   = 'green',
       ['^>%s*[^>%s]'] = 'blue',
       ['^>%s$']       = 'blue',
    }

    20/07/2016 19:12:27.665 CConfig variable changed maildir.max
    ...
    20/07/2016 19:13:03.378 CConfig variable changed maildir.max
    20/07/2016 19:13:03.378 CConfig variable changed maildir.max

So yes, the segfault might be imap-related but it's not clear yet.

**Comment by skx** [comment]
Those maildirs will be ignored - we ignore any maildir which does not contain:

* new/
* cur/
* tmp/

I see that the test-data you have copied is missing tmp/ in the top-level.  Then the sub-folders are missing "new/" + "tmp/".  That explains the "no folders".

**Comment by xipmix** [comment]
Ah, silly me. I added an empty tmp/ and tried again. I do get the segfault, so I guess I will go play in gdb.

    lumail2(89977,0x7fff7a44d000) malloc: *** error for object 0x7fc078464e80: incorrect checksum for freed object - object was probably modified after being freed.
                                                                           *** set a breakpoint in malloc_error_break to debug
                                         Abort trap: 6

Log file contained:

    20/07/2016 22:10:12.564 CConfig variable changed maildir.prefix
    20/07/2016 22:10:12.565 CConfig variable changed maildir.max
    20/07/2016 22:10:12.566 CConfig variable changed global.mailer
    20/07/2016 22:10:12.566 CConfig variable changed global.editor
    20/07/2016 22:10:12.566 CConfig variable changed global.sender
    20/07/2016 22:10:12.566 CConfig variable changed colour.unread
    20/07/2016 22:10:12.566 CConfig variable changed global.history
    20/07/2016 22:10:12.567 CConfig variable changed message.cache
    20/07/2016 22:10:12.567 CConfig variable changed index.sort
    20/07/2016 22:10:13.073 CConfig variable changed maildir.max

**Comment by skx** [comment]
Does commit 937a78690c7857aa547e1eb778e5d15b2a882ca7, which I made to resolve #219, help at all for this crash you're seeing?

**Comment by xipmix** [comment]
It fixes the crash on maildir access. I get a nice cherry-red warning about 'o sent-mail folder defined!', but I am able to access the test maildir. Will test the imap side of things later on.

**Comment by skx** [comment]
Wonderful news, thanks for the prompt update.

Please do report fresh issues as you find them then.  I'll keep running with the address sanitizer flag on, to see if there are more silent errors.

**Comment by xipmix** [comment]
IMAP is now working without segfaulting. Other issues to report but this is good progress.

**Comment by skx** [comment]
Awesome.

I'll fix the handle issue in #220, then push out a new release in the next few days - unless your issues are urgent enough to delay that :)

**Comment by xipmix** [comment]
On Wed, Aug 03, 2016 at 04:24:52AM -0700, Steve Kemp wrote:
> Awesome.
> 
> I'll fix the handle issue in #220, then push out a new release in
> the next few days - unless your issues are urgent enough to delay
> that :)
> 

Good heavens, don't wait for me.
It'll be a little time before I can return my attention to this.
