### ISSUE TITLE
Our unified drawing mode calculates too much.

### ISSUE THREAD

**Issue by skx** [lumail/lumail2#22]
The unified drawing code (`CScreen::draw_text_lines()`) is now used for drawing:

* maildir-mode - Which displays a list of Maildirs
* index-mode - Which displays a list of messages.
* message-mode - Which displays a single message.

In each case the input to that function is a list of strings to display.  One for each row.  This is a unified approach which ensures our navigation only exists in one place - awesome - but the way we're using it is suboptimal.

Consider the case of displaying a list of messages, in index-mode.  Pretend that the Maildir has 1024 messages.  We run this:

* Create an empty array, to hold lines we'll display.
* For each message
      * Call `Message:to_index` to format that message.
      * Add the output to our array.
* Draw the line(s).

This means that although the screen height is only, say 80 rows deep, we calculated the formatting on 1024 messages.  Slowly.

There are two solutions here:

* Only call the formatting function on the messages which are visible.  But that means duplicating the calculation to determine the window into our list of displayable items.
* Ignoring this pain, and instead moving the formatting code into `CMaildir`/`CMessage` and caching it as appropriate.

For a message this makes sense.  A message won't change under us.  For a `CMaildir` we'll need to cache on the `mtime` of the directory.

I suspect the first solution is the neatest, but I'm willing to compromise on the second because it will make scrolling "instant".  (i.e. We pay the price at the time the folder is opened, not on-scroll.  At that point stuff is already cached.)

**Comment by jugglerchris** [comment]
You could have a list of (something like) `pair<bool, string>` (or equivalent), where the bool means "this string has been calculated", ie lazily format each message.
Related questions:
* Are you still allowing sorting the list in Lua?
* Can we have the option for Lua to format an index entry?  I've use this (a change I haven't got around to feeding back - sorry!) currently; combined with Lua sorting I even use this for threading.

**Comment by skx** [comment]
Lua **is** used to format the lists, in a way that I like:

* Maildir list shown in maildir-mode (see `Maildir.to_string()` in `lumail2.lua`).
* Message list shown in index-mode (see `Message.to_index()` in `lumail2.lua`).
* Message content - shown in message mode (see `Message.to_string()` in `lumail2.lua`).

(I'll rename them "Message.format()" and "Maildir.format()" for index-display.  Message.to_string() is good for displaying in message-mode).

Sorting is not yet handled.  It will be.  Patches/comments welcome.

The single biggest blocker at the moment is that I need to make sure I'm using `std::shared_ptr<>` globally.  As per the comments in `maildir_view.cc` and `index_view.cc`.  At the moment I'm creating new objects too often, which means the proposed caching wouldn't work anyway!

**Comment by jugglerchris** [comment]
Ah, sorry for my confusion.  I hadn't realised that Maildir.to_string() etc. were Lua functions and not methods on a C++ object!  In which case all looks great so far.  :-)

**Comment by skx** [comment]
I'm pretty pleased with the way things are delegated to Lua like that.

For example `lua`-mode just displays the output of the function [lua_mode](https://github.com/lumail/lumail2/blob/master/lumail2.lua#L217).  So lines returned from that function are displayed as-is, complete with left/right/up/down scrolling all being handled.

That's how I expect we'll list MIME-parts, and attachments, etc.  Just write a quick new mode to return a list of lines that can be drawn and selected.

**Comment by skx** [comment]
Created two bugs to track these :

* #27 
* #28 

Struggling with them both, but perhaps it'll make more sense when I've had a few days off.

**Comment by skx** [comment]
I think the plan here is to remove the C++/Lua divide and allow the Lua mode to format all the display of the maildirs/indexes.  This is described in #30.

**Comment by skx** [comment]
Yeah with #30 implemented this can close.  Yes we'll still format "too much", but the implementation is clean and we have a much clearer divide:

* We have a view-class in C++
* Which just defers to `$mode_view()` in Lua.

The operations that lua makes, calling `unread_messages()`, `header()`, etc, can be cached at the C++ layer.  And this will then become a non-issue.

**Comment by skx** [comment]
Closing this as a non-issue.
