### ISSUE TITLE
Tentative roadmap for 2.9

### ISSUE THREAD

**Issue by skx** [lumail/lumail2#234]
The current release is 2.8.
## 2.9
- We're going to add new `index.limit` setting, `attach` to show only messages with attachments.
  - This will nicely complement the existing values "`new`", "`today`", and "`all`".
  - At the moment I use the hack: `Config:set( "index.limit", "] A -")`
- Overhaul [our website](https://lumail.org/), via [the source](https://github.com/lumail/lumail.org).
- Use profiling to improve performance.  The two key areas to concentrate upon are:
  - caching
    - Optional redis?
  - message/maildir sorting - both of which could be improved.  (Sorting my largest mailbox takes 8 seconds :( )
- Automate more of my mail-utils jobs directly in lumail and see what primitives we're missing
- Add async screen updates.  i.e. blocking operations such as opening a maildir, and sorting the messages, should perform screen updates.
  - The new `Screen:redraw()` primitive will help with that.
- Simplify the lua calling by using a single method with a format-string for arguments.  Right now we have several methods which just feels bad:
  - function2table
  - functiona2table
  - get_variable
  - function2string
- Rework `log_message`.  Adding `CLuaLog` everywhere made it obvious we have a choice between "log everything" and "log nothing".
  - We should reconsider logging and _also_ allow log-levels.  e.g. "`Config:set( "log.level"," lua|maildir|debug" )`", or similar.
  - Details are hazy, but it would be nice to setup logs based on the _area_ of the code in question, be it folder-operations, message-operations, low-level lua calls, or **everything**.
- Your bug here?

**Comment by skx** [comment]
> i.e. blocking operations such as opening a maildir, and sorting the messages, should perform screen updates. 

Suspect this might not be possible, since Lua will block, but it would be nice to see.

**Comment by skx** [comment]
Pretty much everything is done here - but I want to see if I can speedup the opening of a large Maildir before making a new release.

Our sorting is cached, so while an initial folder open might take "a while" subsequent opens are acceptable.  But reading 50,000 messages from a Maildir is still too slow - first time is slowest, but second time is still slower - and that should probably have the `index.format` setting(s) cached.

To be explicit

* Getting all messages should be faster.
    * Just need to check we're not creating/destroying Message objects too much here I think.
* The formatting of many messages is expected to suck the first time:
    * Since the default view involves reading `Subject:`, `From:` headers, etc, which necessitate parsing each message.
* Formatting messages a second time should be OK because `Message:format()` will be cached.

**Comment by skx** [comment]
Pretty much done here - There are speed gains to be made, but I'm happy with the current state.

The new format-string work is useful.  The new threading code is exceptionally nicely done, and I think it deserves to be shown off (i.e. new screenshots).

**Comment by fischerling** [comment]
One wish for convenience:

We should be able to invalidate our formatting cache. So that format changes are
immediately visible without purging the whole cache.

This should be done if any of our {attachment,index,maildir}.format changes or
if we switch sorting method from or to threads, because of its indentation.

**Comment by skx** [comment]
Excellent suggestion, thanks for making it.  I believe the previous commit does that but I'll await your confirmation before pushing a release.

**Comment by fischerling** [comment]
8b09b0dc32748f955c97956672a0797713179dd1 looks good and it seems to work.

**Comment by skx** [comment]
Released.  Thanks again for your awesome threading support.
