### ISSUE TITLE
Describtion of the code style

### ISSUE THREAD

**Issue by fischerling** [lumail/lumail2#252]
It would be nice if you could write some short lines about the lua code style.

Or add a lua formatter to the make indent target.

**Comment by skx** [comment]
Unfortunately I couldn't ever find a Lua pretty-printer/formatter, so my general approach is to run in emacs:

* Select-all
* M-x indent-region

I know that I'm not as consistent as I could be with spacing, and even trailing `;` characters (which I prefer not to be present).    If you do happen to find something then I'd be enormously grateful.

**Comment by fischerling** [comment]
The result of a short search:

+ https://github.com/batrick/lunadry
+ https://github.com/luadist/luapretty

I only tested lunadry because it has only few dependencies. 
It is not very easy configurable but I am happy with the result.

In the absence of a official lua code style guide, like pep-8 for python, we
could try to follow http://lua-users.org/wiki/LuaStyleGuide or develop and
document our own.

**Comment by skx** [comment]
lunadry has few dependencies, and the default output looked OK to me so I'll pick that.

I'll commit something README.md/HACKING.md/CONTRIBUTING.md later today, and say "Use that".

Thanks for raising it, I know I've not been as consistent as I should and so this is useful to think about.
