### ISSUE TITLE
We could handle message-deletion more quickly.

### ISSUE THREAD

**Issue by skx** [lumail/lumail2#255]
If you have a maildir with 100+ messages, and you delete one then the screen flickers as it re-reads the Maildir from scratch, and applies sorting.

Given that we have the global set of messages what we could do is just remove the single entry from the set, and avoid re-reading.

The code in question is either:

(index)

```
   -- Flush the cached message-list, and get the updated set.
   global_msgs = {}
   local msgs = get_messages()
```

(maildir)

```
  -- Flush the cached message-list
  global_msgs = {}
```

I think that's a safe change to make - instead we just call `table.remove( global_msgs, offset)`.  Will test before I commit.

**Comment by skx** [comment]
I realized after implementing this that it wasn't such a great idea; so for the moment I'm closing without submitting.

**Comment by fischerling** [comment]
What was not working as expected ?
When I tried to speedup the deletion it seemed to work.

**Comment by skx** [comment]
Honestly I'm not sure that I remember right now.  It did seem like a simple approach that should have been safe.
