### ISSUE TITLE
Bogus parsing of a specific (spam) message.

### ISSUE THREAD

**Issue by skx** [lumail/lumail2#262]
The attached message was received today, and is pasted in full.  It shows a single `multipart/related` MIME-part, and the attachment isn't visible.

As a mitigating factor `mutt` does a horrible job with it too.

[bogus.msg.txt](https://github.com/lumail/lumail2/files/645387/bogus.msg.txt)

**Comment by jugglerchris** [comment]
I had a look as I've been looking into MIME parsing recently.  It's invalid; the MIME boundary has become separated from the `Content-Type` header and has ended up in the `X-Priority` header instead.  I suspect the spam sender has tried shuffling header lines around to evade duplicate detections...

**Comment by skx** [comment]
Thanks for looking.

I'll close this as "bogus mail" rather than "bogus parsing" then.
