### ISSUE TITLE
Deleting messages is broken.

### ISSUE THREAD

**Issue by skx** [lumail/lumail2#266]
Now I remember what the problem was when I looked at it in #255, as implemented by pull request #264.

* Open a folder containing five messages.
* Scroll down twice, by pressing `j` + `j`.
* View the resulting message, by pressing `enter`.
* Hit `d` a bunch of times.
* You'll see `no message selected!`
* The *last* message will not be deleted.

Probably a simple off-by-one.  Will look tomorrow night, unless I get beaten to it :)

**Comment by skx** [comment]
This is easy to solve.   The two obvious cases are:

* In message_view -> Should advance to the next message.
* In index_view -> Should advance to the next message.

The first one is the only one that I've looked at, but the cause is clear:

      --
      -- WARNING: index.current is 0 based!
      --
      local msg_index = Config.get_with_default("index.current", 0) + 1

      ... deletion happens ...

      -- select next message
      if msg_index < (#global_msgs) then
        Global:select_message(global_msgs[msg_index + 1])
      end

The problem is we use `msg_index + 1`.  

* Assume we have two messages.
* The index is 0.
* Delete that first message.
* We should move to the second, but we don't.

The problem is that when we remove the message from the `global_msgs` table we've decreased the size by one, so we want to actually select the same offset - it's just because there is one fewer message, total, we'll advance.

i.e.

* Select message 0
* Delete message 0.
* We __should not__ then select message 1 - because that will not exist.
* Instead we select message 0, but that is the __new__ 0, not the old one.

Suspect fixing this would have been faster than thinking it through and writing this message :)

**Comment by fischerling** [comment]
You are right, I changed the collection but didn't consider that I modify
it.

Are you going to fix this ?

**Comment by skx** [comment]
If you fix it before tomorrow then I'll accept your merge request, if not I'll handle it then.

Just a minor thing, but it caught me out when I did it too.  I just forgot the details :)
