### ISSUE TITLE
Threaded mail doesn't show as expected.

### ISSUE THREAD

**Issue by skx** [lumail/lumail2#269]
The following settings should be sufficient:

       Config:set( "index.sort", "threads" )
       Config:set( "threads.sort", "date" );
       Config:set( "threads.output", "#;`;-> ")

The last setting, with the nested/prefix character, doesn't seem to work for me.  Though the threads _are_ gloriously sorted :)

See if @fischerling has input - could be I'm just doing something daft.

**Comment by fischerling** [comment]
What exactly is not working as expected ?

I tested your formatting string and it worked.

**Comment by skx** [comment]
Sorry I might have been too vague.

I don't see _any_ of the prefix-characters being displayed, at all.  e.g. if I set the following I see zero occurrences of "N#":

    Config:set( "threads.output", "1#;2#;3#")

**Comment by fischerling** [comment]
Do you get any errors ?
Have you tried changing lumail2.lua:536 directly ?
Have you erased your cache ?

**Comment by skx** [comment]
> Do you get any errors ?

None.

> Have you tried changing lumail2.lua:536 directly ?

I added some diagnostics just to be sure:
     +    Panel:append( "Indent: " .. threads_output_indent  .. " root " .. threads_output_root .. " output " ..  threads_output_sign );

In the panel I see that has worked:

     INFO: Selected /home/skx/Maildir/people-addy with 0 messages.
     Indent: # root ` output ->
     Sort method threads took 0 seconds with 53 messages

It's just that I don't see those characters be displayed.  My view looks like the attached image.

> Have you erased your cache ?

Yes, but that was a good reminder that this would be at fault :)

![blah](https://cloud.githubusercontent.com/assets/735291/21750350/e28b2090-d5b9-11e6-9566-5e2e9744b382.jpg)

**Comment by skx** [comment]
I'm an idiot.   Threading is __disabled__ if `index.fast` is set.

Note we have two calls to `object:format` in `index_view()` - only one of them sets up the (optional) argument.

**Comment by skx** [comment]
$ git diff
       diff --git a/lumail2.lua b/lumail2.lua
       index 0115bcd..85bdab7 100644
       --- a/lumail2.lua
       +++ b/lumail2.lua
       @@ -2319,7 +2319,7 @@ function index_view ()
              -- Only show the message if it will fit on the screen
              --
              if (offset >= min) and (offset < max) then
       -        str = object:format()
       +        str = object:format(threads_indentation[object])
              else
                str = "INVISIBLE - Outside the viewport!"
              end

Results in a better view:

![blah2](https://cloud.githubusercontent.com/assets/735291/21750374/5fde8fd2-d5ba-11e6-908c-521000cca514.jpg)
