### ISSUE TITLE
CMessage wrapper needs to use std::shared_ptr.

### ISSUE THREAD

**Issue by skx** [lumail/lumail2#27]
This should be an issue only to the binding code.

**Comment by skx** [comment]
Ugh.  This is a pain.  My attempts to convert just result in segfaults in CMessageView.

I will need to experiment further.  I'm sure I'm missing something obvious.

**Comment by skx** [comment]
This is my initial attempt, which failed badly.

     diff --git a/src/message_lua.cc b/src/message_lua.cc
     index 2c3db2c..f5a9b79 100644
     --- a/src/message_lua.cc
     +++ b/src/message_lua.cc
     @@ -1,5 +1,5 @@
      /**
     - * $FILENAME - $TITLE
     + * message_lua.cc - Bindings for the CMessage C++ object.
       *
       * This file is part of lumail - http://lumail.org/
       *
     @@ -52,22 +52,24 @@ int l_CMessage_constructor(lua_State * l)
      {
          const char *name = luaL_checkstring(l, 1);
      
     -    CMessage **udata = (CMessage **) lua_newuserdata(l, sizeof(CMessage *));
     -    *udata = new CMessage(name);
     +    /**
     +     * Allocate a new object.
     +     */
     +    std::shared_ptr<CMessage> *udata = (std::shared_ptr<CMessage> *)lua_newuserdata(l, sizeof(std::shared_ptr<CMessage>*));
     +    *udata = std::shared_ptr<CMessage>(new CMessage(name));
      
          luaL_getmetatable(l, "luaL_CMessage");
     -
          lua_setmetatable(l, -2);
      
          return 1;
      }
      
      /**
     - * Test that the object is a CMessage.
     + * Test that the object is a std::shared_ptr<CMessage>.
       */
     -CMessage * l_CheckCMessage(lua_State * l, int n)
     +std::shared_ptr<CMessage> *l_CheckCMessage(lua_State * l, int n)
      {
     -    return *(CMessage **) luaL_checkudata(l, n, "luaL_CMessage");
     +    return (std::shared_ptr<CMessage>*) luaL_checkudata(l, n, "luaL_CMessage");
      }
      
      /**
     @@ -75,9 +77,8 @@ CMessage * l_CheckCMessage(lua_State * l, int n)
       */
      int l_CMessage_path(lua_State * l)
      {
     -    CMessage *foo = l_CheckCMessage(l, 1);
     -
     -    lua_pushstring(l, foo->path().c_str());
     +    std::shared_ptr<CMessage> *foo = l_CheckCMessage(l, 1);
     +    lua_pushstring(l, (*foo)->path().c_str());
          return 1;
      }
      
     @@ -86,11 +87,11 @@ int l_CMessage_path(lua_State * l)
       */
      int l_CMessage_header(lua_State * l)
      {
     -    CMessage *foo = l_CheckCMessage(l, 1);
     +    std::shared_ptr<CMessage> *foo = l_CheckCMessage(l, 1);
      
          /* Get the header. */
          const char *str = luaL_checkstring(l, 2);
     -    std::string result = foo->header(str);
     +    std::string result = (*foo)->header(str);
      
          /* set the retulr */
          lua_pushstring(l, result.c_str());
     @@ -106,8 +107,8 @@ int l_CMessage_headers(lua_State * l)
          /**
           * Get the headers.
           */
     -    CMessage *foo = l_CheckCMessage(l, 1);
     -    std::unordered_map < std::string, std::string > headers = foo->headers();
     +    std::shared_ptr<CMessage> *foo = l_CheckCMessage(l, 1);
     +    std::unordered_map < std::string, std::string > headers = (*foo)->headers();
      
      
          /**
     @@ -142,12 +143,12 @@ int l_CMessage_headers(lua_State * l)
       */
      int l_CMessage_parts(lua_State * l)
      {
     -    CMessage *foo = l_CheckCMessage(l, 1);
     +    std::shared_ptr<CMessage> *foo = l_CheckCMessage(l, 1);
      
          /**
           * Get the parts, and count.
           */
     -    std::vector < CMessagePart * >parts = foo->get_parts();
     +    std::vector < CMessagePart * >parts = (*foo)->get_parts();
      
          lua_createtable(l, parts.size(), 0);
          int i = 0;
     @@ -173,7 +174,7 @@ int l_CMessage_parts(lua_State * l)
       */
      int l_CMessage_flags(lua_State * l)
      {
     -    CMessage *foo = l_CheckCMessage(l, 1);
     +    std::shared_ptr<CMessage> *foo = l_CheckCMessage(l, 1);
      
          /**
           * Are we setting the flags?
     @@ -183,13 +184,13 @@ int l_CMessage_flags(lua_State * l)
          if (n > 1)
          {
              const char *update = luaL_checkstring(l, 1);
     -        foo->set_flags(update);
     +        (*foo)->set_flags(update);
          }
      
          /**
           * Now get the flags
           */
     -    lua_pushstring(l, foo->get_flags().c_str());
     +    lua_pushstring(l, (*foo)->get_flags().c_str());
          return 1;
      }
      
     @@ -198,9 +199,8 @@ int l_CMessage_flags(lua_State * l)
       */
      int l_CMessage_destructor(lua_State * l)
      {
     -    CMessage *foo = l_CheckCMessage(l, 1);
     -    delete foo;
     -
     +  //    std::shared_ptr<CMessage> *foo = l_CheckCMessage(l, 1);
     +  //    delete(foo);
          return 0;
      }

**Comment by jugglerchris** [comment]
Here's an update which goes on top of the patch above which I think fixes it.  The two main issues:
* You can't do *(shared ptr *)some_memory = shared_ptr<>() - you have to construct it in place (placement new) and similarly destruct.
* Pass around actual share_ptr instances rather than pointers to (shared) pointers.

```diff
diff --git a/src/message_lua.cc b/src/message_lua.cc
index f5a9b79..e206da4 100644
--- a/src/message_lua.cc
+++ b/src/message_lua.cc
@@ -55,7 +55,25 @@ int l_CMessage_constructor(lua_State * l)
     /**
      * Allocate a new object.
      */
-    std::shared_ptr<CMessage> *udata = (std::shared_ptr<CMessage> *)lua_newuserdata(l, sizeof(std::shared_ptr<CMessage>*));
+    void *ud = lua_newuserdata(l, sizeof(std::shared_ptr<CMessage>*));
+    if (!ud)
+    {
+        /* Error - couldn't allocate the memory */
+        return 0;
+    }
+    /* We can't just do *(shared_ptr<...> *)ud = shared_ptr<>... since
+     * it will try to call the assignment operator on the object at *ud,
+     * but there isn't one (so it tries to free random junk).
+     *
+     * Instead, construct the new shared pointer in the memory we've just
+     * allocated.
+     */
+    std::shared_ptr<CMessage> *udata = new (ud) std::shared_ptr<CMessage>();
+
+    /*
+     * Now that we have a valid shared_ptr pointing to nothing, we can
+     * assign the final value to it.
+     */
     *udata = std::shared_ptr<CMessage>(new CMessage(name));
 
     luaL_getmetatable(l, "luaL_CMessage");
@@ -67,9 +85,22 @@ int l_CMessage_constructor(lua_State * l)
 /**
  * Test that the object is a std::shared_ptr<CMessage>.
  */
-std::shared_ptr<CMessage> *l_CheckCMessage(lua_State * l, int n)
+std::shared_ptr<CMessage> l_CheckCMessage(lua_State * l, int n)
 {
-    return (std::shared_ptr<CMessage>*) luaL_checkudata(l, n, "luaL_CMessage");
+    void *ud = luaL_checkudata(l, 1, "luaL_CMessage");
+    if (ud)
+    {
+        /* Get a pointer to the shared_ptr object */
+        std::shared_ptr<CMessage> *ud_msg = static_cast<std::shared_ptr<CMessage> *>(ud);
+
+        /* Return a copy (of the pointer) */
+        return *ud_msg;
+    }
+    else
+    {
+        /* otherwise a null pointer */
+        return std::shared_ptr<CMessage>();
+    }
 }
 
 /**
@@ -77,8 +108,8 @@ std::shared_ptr<CMessage> *l_CheckCMessage(lua_State * l, int n)
  */
 int l_CMessage_path(lua_State * l)
 {
-    std::shared_ptr<CMessage> *foo = l_CheckCMessage(l, 1);
-    lua_pushstring(l, (*foo)->path().c_str());
+    std::shared_ptr<CMessage> foo = l_CheckCMessage(l, 1);
+    lua_pushstring(l, foo->path().c_str());
     return 1;
 }
 
@@ -87,11 +118,11 @@ int l_CMessage_path(lua_State * l)
  */
 int l_CMessage_header(lua_State * l)
 {
-    std::shared_ptr<CMessage> *foo = l_CheckCMessage(l, 1);
+    std::shared_ptr<CMessage> foo = l_CheckCMessage(l, 1);
 
     /* Get the header. */
     const char *str = luaL_checkstring(l, 2);
-    std::string result = (*foo)->header(str);
+    std::string result = foo->header(str);
 
     /* set the retulr */
     lua_pushstring(l, result.c_str());
@@ -107,8 +138,8 @@ int l_CMessage_headers(lua_State * l)
     /**
      * Get the headers.
      */
-    std::shared_ptr<CMessage> *foo = l_CheckCMessage(l, 1);
-    std::unordered_map < std::string, std::string > headers = (*foo)->headers();
+    std::shared_ptr<CMessage> foo = l_CheckCMessage(l, 1);
+    std::unordered_map < std::string, std::string > headers = foo->headers();
 
 
     /**
@@ -143,12 +174,12 @@ int l_CMessage_headers(lua_State * l)
  */
 int l_CMessage_parts(lua_State * l)
 {
-    std::shared_ptr<CMessage> *foo = l_CheckCMessage(l, 1);
+    std::shared_ptr<CMessage> foo = l_CheckCMessage(l, 1);
 
     /**
      * Get the parts, and count.
      */
-    std::vector < CMessagePart * >parts = (*foo)->get_parts();
+    std::vector < CMessagePart * >parts = foo->get_parts();
 
     lua_createtable(l, parts.size(), 0);
     int i = 0;
@@ -174,7 +205,7 @@ int l_CMessage_parts(lua_State * l)
  */
 int l_CMessage_flags(lua_State * l)
 {
-    std::shared_ptr<CMessage> *foo = l_CheckCMessage(l, 1);
+    std::shared_ptr<CMessage> foo = l_CheckCMessage(l, 1);
 
     /**
      * Are we setting the flags?
@@ -184,13 +215,13 @@ int l_CMessage_flags(lua_State * l)
     if (n > 1)
     {
         const char *update = luaL_checkstring(l, 1);
-        (*foo)->set_flags(update);
+        foo->set_flags(update);
     }
 
     /**
      * Now get the flags
      */
-    lua_pushstring(l, (*foo)->get_flags().c_str());
+    lua_pushstring(l, foo->get_flags().c_str());
     return 1;
 }
 
@@ -199,8 +230,17 @@ int l_CMessage_flags(lua_State * l)
  */
 int l_CMessage_destructor(lua_State * l)
 {
-  //    std::shared_ptr<CMessage> *foo = l_CheckCMessage(l, 1);
-  //    delete(foo);
+    void *ud = luaL_checkudata(l, 1, "luaL_CMessage");
+    if (ud)
+    {
+        /* Get a pointer to the shared_ptr object */
+        std::shared_ptr<CMessage> *ud_msg = static_cast<std::shared_ptr<CMessage> *>(ud);
+
+        /* We need to destruct the pointer in place; it will decrement
+         * the reference count as usual.  After this the user data object
+         * becomes just plain memory again. */
+        ud_msg->~shared_ptr<CMessage>();
+    }
     return 0;
 }
 

```

**Comment by skx** [comment]
Thanks for the contribution; that's the kind of update that I think would be useful.

Unfortunately I'm getting segfaults when viewing Index-mode with this update.  I think there's something screwy in `CMessageView::get_message`, even despite my attempts to replicate the constructor.  The ultimate aim is that we **don't** create a new message for each line, instead `CGlobalState::get_messages()` will persist - and at that point caching the output of calling `Message.to_index()` will a) work and b) be useful.

**Comment by skx** [comment]
PS.  It may be the case that allowing CMessage objects to be *created*/*destroyed* from Lua is the mistake I'm making.

I'm thinking about that at the moment.  Accessing the current maildir/message is obviously desirable.  Also fetching the current messages in a maildir.  But creating new ones?  This is where I'm getting the problem with the lua-destructor changing things under the feet of C++ and causing the pain.

I think it should be possible to get `std::shared_ptrs` to handle that, but given the pain maybe rethinking things and avoiding the constructor/destructor pain is the way to go.

Heading away for the weekend, so I'll think away from distractions.

**Comment by jugglerchris** [comment]
I've looked into it a bit more.  I'd only updated message_lua.cc, not the other places which still put raw pointers in.  I think I've fixed those too - PR on the way.

**Comment by skx** [comment]
D'oh.  Thanks.

It did cross my mind early this morning that a solution might be to stop accessing these objects in C++.  If we add the function `current_maildir`, `message` and `maildirs` we could move the drawing entirely into Lua.  Just like in lua-mode.  That might be something to consider for the future too.  It allows you to sort by headers/stuff if you wished, and allows more control over the drawing.

The draw function would literally just be:

       function index_view() 
            local ret={}
            local messages = messages()
            for k,v in ipairs(messages) do
                table.insert( ret, v:format() )
            end
            return ret 
       end

This is kinda-unrelated.  But I guess the biggest part of the code where we work with these objects is in the draw-modes.  And really all we want is an array of formatted object-output.

**Comment by skx** [comment]
#30.
