### ISSUE TITLE
delete_all no longer works.

### ISSUE THREAD

**Issue by skx** [lumail/lumail2#271]
Will need to look into it, but it seems to stop after 5-10 messages.

Almost certainly a result of changes to the deletion code.

**Comment by fischerling** [comment]
We have again a change during iteration bug.

1. We get a reference to our global message table in `delete_all()`
2. We iterate the reference and call `Message.delete` at `Functional.map()`
3. `Message.delete()` change the global message table which is the same as
our local one. (No deep copy)
4. So we change our local message table during iteration => Indeterministic
behaviour.


## Solution

Change `Functional.map` and `Functional.object_map` to iterate the collection
from the back.

**Comment by skx** [comment]
Good analysis, I agree completely.
