### ISSUE TITLE
Index formatting doesn't necessarily pad correctly.

### ISSUE THREAD

**Issue by skx** [lumail/lumail2#277]
The index-formatting is now template-driven, which is awesome, but the padding works on ASCII not UTF.  This means that special characters take up more width in theory than in practice.

For example:

![foo](https://cloud.githubusercontent.com/assets/735291/23089500/4c1a9afc-f592-11e6-9f83-38f24995fd8c.jpg)

Here the umlauted character counts as two characters wide, but only consumes a single space, throwing off the alignment.

**Comment by skx** [comment]
The following program demonstrates the problem:

      x = "Müller"
      print( x )
      print( "Length is " .. x:len() )

      x = "Muller"
      print( x )
      print( "Length is " .. x:len() )

Producing this output:

       $ lua5.2 ./t.lua 
       Müller
       Length is 7
       Muller
       Length is 6

**Comment by skx** [comment]
Test cased added e9f297f81453996a13e25e8bb774b821bf3ba56b

**Comment by fischerling** [comment]
I don't think this is completely fixed.

The left shows the padding after the commit and the right before. 
![2017-02-18-122622_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1218430/23092972/ce38cdb2-f5d6-11e6-96fe-2c0bbebdc9b2.png)

Some strings with ö or ü are still not aligned correctly.

**Comment by skx** [comment]
Appreciate the screenshot, thanks! 

I thought the test-case would ensure that this was fixed as expected.

Can you confirm that you've flushed your cache, as old values might still be lingering from that.  (Though they should be versioned ..)

If you have flushed then please feel free to reopen and I'll try to reproduce.
