### ISSUE TITLE
imap dependency package correction

### ISSUE THREAD

**Issue by jaromil** [lumail/lumail2#278]
The correct package name in IMAP.md is `libnet-imap-client-perl`

BTW thanks for the nice software :^) I'm testing it specifically for the imap functionality, trying to get a list of date sorted messages from an imap folder...

**Comment by skx** [comment]
Thanks for the bug-report.  

I hope you find what you're looking for in the IMAP code, but if you have questions/problems. feel free to report bugs, or drop me a mail :)
