### ISSUE TITLE
Index formatting is still broken

### ISSUE THREAD

**Issue by fischerling** [lumail/lumail2#279]
As mentioned in #277 I still experience broken formatting after 3361097.

I attach a small [test maildir](https://github.com/lumail/lumail2/files/790830/padding_test.zip) 
with messages, that have incorrect formatted Sender fields.

**Comment by fischerling** [comment]
That was easy thanks :)

**Comment by skx** [comment]
You're welcome :)

I verified the string length was correctly being counted, and that made it obvious it was "just" an off-by-one.

**Comment by fischerling** [comment]
Haha. Now my test maildir has correct padding but my INBOX has 3 different Sender lenghts.
![2017-02-21-184128_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1218430/23177117/f5f7ade6-f865-11e6-89e9-a1be1ee597a5.png)
left after dba9242; right before

**Comment by skx** [comment]
Uggh.

Notice how the entries that stick to the right are too short?  Might be an off by one in the addition of a padding character?

**Comment by fischerling** [comment]
Also the padding tests are broken after dba9242.

**Comment by skx** [comment]
Grr.  I'll revert, and attack it again tomorrow.

**Comment by fischerling** [comment]
I logged the length of our input values in Message:format() with

```diff
diff --git a/lumail2.lua b/lumail2.lua
index 84b99ee..e798c09 100644
--- a/lumail2.lua
+++ b/lumail2.lua
@@ -2345,6 +2345,7 @@ function Message:format (thread_indent, index)


     }))
+  Log:log("format", "len of sender <" .. sender .. ">: " .. sender:len())

   --
   -- If the message is unread then show it in the "unread" colour
```
and the lengths of the to small Senders are correct in the log.

**Comment by skx** [comment]
OK so the length of the string is correct, that does imply that the issue is off-by-one in the padding/truncation.

**Comment by fischerling** [comment]
### Observations

* Padding works fine.
* Trimming works fine if the utf8 runes are cut of.
* Trimming is broken by 1 for each utf8 rune in the resulting string.

I made  another [test maildir](https://github.com/lumail/lumail2/files/794867/padding_test.zip) to demonstrate this behaviour.

### Conclusion

Broken is the trimming at string_utilities.lua line 82-84, because
we use the utf8-aware len function to cut of characters. If there is a utf8
rune in the resulting string we cut of two characters not one.

**Comment by skx** [comment]
I appreciate your diagnostics and fix, thank you :)

(Got distracted with [other projects](/skx/e-comments) last night!)
