### ISSUE TITLE
get_messages() fails if #msgs < Screen:width()

### ISSUE THREAD

**Issue by fischerling** [lumail/lumail2#291]
864   local msgs = Global:current_messages()
    865
    866   --
    867   -- How many steps do we expect to update for our progress-bar?
    868   --
    869   local steps = math.floor(#msgs / Screen:width())
    870
    871   --
    872   -- Now apply any limit which should be present.
    873   --
    874   -- Valid limits are:
    875   --
    876   --   All      -> All messages.
    877   --   New      -> All messages which are unread.
    878   --   Today    -> Show messages arrived today.
    879   --  "pattern" -> All messages matching the given pattern.
    880   --
    881   local limit = Config.get_with_default("index.limit", "all")
    882
    883   if limit == "all" then
    884     --
    885     -- "All"
    886     --
    887     --  This could be simplified to the following:
    888     --     global_msgs = msgs
    889     --
    890     for i, o in ipairs(msgs) do
    891       -- Bump our progress-bar
    892       if math.fmod(i, steps) then
    893         Progress:show_percent(i, #msgs)
    894       end

if #msgs is less than the screen width `steps` will be 0 and math.fmod will fail
with: `bad argument #2 to 'fmod' (zero)`.

I don't consider myself familiar enough with the progress bar code to fix it.

**Comment by skx** [comment]
That's an interesting bug report, but I cannot reproduce it at all.

If I open a folder with 4 messages,  i.e. less than the screen-width, and yet I see nothing wrong.  I can add logging:
 
      local steps = math.floor(#msgs / Screen:width())
      info_msg( "Steps is " .. steps )

Then some more:

    for i, o in ipairs(msgs) do
      -- Bump our progress-bar
      if math.fmod(i, steps) then
         Progress:show_percent(i, #msgs)
         info_msg( "Progress " .. i )
      end

But when I do that I just see:

       |Sort method file took 0 seconds with 4 messages
      │INFO: Steps is 0
      │INFO: Progress 1
      │INFO: Progress 2
      │INFO: Progress 3
      │INFO: Progress 4
      │Sort method file took 0 seconds with 4 messages

No error from `fmod`.

Do you have a simple way to reproduce this?

**Comment by skx** [comment]
FWIW I don't see an error from `fmod` interactively:

        $ lua5.2 
        Lua 5.2.3  Copyright (C) 1994-2013 Lua.org, PUC-Rio
        > print( math.fmod(0,3))
        0
        > print( math.fmod(3,0))
        -nan
        > 

I get the same `nan` - but no error - on Lua 5.1. too.

**Comment by fischerling** [comment]
With lua 5.3.4 I get the following error:

    Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
    > math.fmod(3,0)
    stdin:1: bad argument #2 to 'fmod' (zero)
    stack traceback:
            [C]: in function 'math.fmod'
            stdin:1: in main chunk
            [C]: in ?

**Comment by skx** [comment]
OK that's hint-enough for me, I'll upgrade to 5.3 and then I guess I should be able to reproduce :)

**Comment by fischerling** [comment]
Thanks :)

Lua debugging would be more convenient if we print the lua error reason to stderr and to the log.
Now there is only `FAILED  - Error in index_view` printed to stderr.
