### ISSUE TITLE
Recipients "to"-field in Config:set( "index.format", ...)?

### ISSUE THREAD

**Issue by RquasiR** [lumail/lumail2#294]
Couldn't we get the recipients "to"-field for use in the Config:set( "index.format", ...)?

I tried a sort of work-around in function Message:format (thread_indent,index):

 ###  -- Basics from the message
  local flags   = self:flags()
  local subject = self:header "Subject"
  local sender  = self:header "From"
  local date    = self:header "Date"
  local id      = self:header "Message-ID"
  **local to      = self:header "To"**

and there:

  ### --  Format this message for display
  local output = (string.interp(format, {
                                   flags         = flags,
                                   message_flags = m_flags,
                                   sender        = sender,
                                   email         = email,
                                   name          = name,
                                   indent        = thread_indent,
                                   subject       = subject,
                                   number        = index,
                                   date          = date,
                                   id            = id,
                                   **to            = to,**

        }))

It works as long as I don't do "^W" to finish lumail2 and I don't re-invoke lumail2 again. So I assume
the error I get is connected with the cache and my "work-around" isn't good enough. 

Could we get officially this feature, please?

Rudolf

**Comment by skx** [comment]
Absolutely :)

I'll rename it `recipient` to match with the use of `sender` for the `From:` header, but that aside it's an obvious omission and we should have it.
