### ISSUE TITLE
Add build instructions/dependencies

### ISSUE THREAD

**Issue by winks** [lumail/lumail2#48]
On Debian testing:

```
apt-get install liblua5.2-dev libgmime-2.6-dev libglibmm-2.4-dev libncursesw5-dev
```
And that's without g++ and the stuff I already installed by chance.

**Comment by skx** [comment]
That's the obvious dependency list, apart from `build-essential`, and `make`.

I'll document shortly, something I had put off until the first snapshot release and website overhaul - which I expect will happen sometime over the weekend.

**Comment by winks** [comment]
Sure. no worries. Was just trying out to build and quickly test it and thought I'd write down results for the few minutes I spent.
