### ISSUE TITLE
Our code documentation needs more work.

### ISSUE THREAD

**Issue by skx** [lumail/lumail2#53]
Perhaps I don't understand doxygen very well, but I found that if I put a comment-block above a function in the C++ code __AND__ in the header-file I'd get repeated documentation.

On that basis I converted all the header-files to have comments of the form:

     /*
      * This is ignored by doxygen .. 
      */

That has lead to a lot of warnings about member variables not being documented though.  I need to work through, class by class, and ensure each one has decent documentation.

> That was the rational for inventing a `Singleton` (template) base-class.  It makes intent easier to see, and makes the documentation prettier.

**Comment by skx** [comment]
See #55. for more neatness.

**Comment by jugglerchris** [comment]
I would do the opposite - put the Doxygen comments in the header files, and leave them out of the main source.  The header file is where you'd look for API info, and I don't see the benefit to duplicating them.

**Comment by skx** [comment]
I can't argue with that...

I'll change over once I've finished with #56.
