### ISSUE TITLE
Horizontal scrolling doesn't work

### ISSUE THREAD

**Issue by skx** [lumail/lumail2#57]
To produce:

* Load the program: `./lumail2 --load-file ./lumail2.lua`
* Press `L` to enter Lua-mode.
* Press "`l`" to scroll right one character.
* Notice that the text jumps more than expected.

This is because the lines are beginning with `\t` and length is calculated by characters.

Solution:

* The line-drawing code needs to replace `\t` with N spaces.
* Setup `global.tab.spacing`, or similar, to define the width of a tab-stop.  (Default 8.)

**Comment by jugglerchris** [comment]
That doesn't fully solve the problem.  There are many other characters which don't have the same width as the number of bytes - ie most non-ASCII Unicode characters.

When I did smarter wrapping in Lua for lumail1, I added a primitive to calculate the display width of a string:
https://github.com/jugglerchris/lumail/commit/eb2ba80a316afa774556558eaed535ea2f1c3a31
The tab expansion is still needed (and replacing \t with N spaces isn't quite right - you need to know what column it starts from, but you probably know that.  :-) ).

**Comment by skx** [comment]
Fixed in c1a246a1e44f373c319bcff7e5505694ef8a2e8b
