### ISSUE TITLE
Compilation fails with gcc 4.6

### ISSUE THREAD

**Issue by trou** [lumail/lumail2#58]
Trying to compile fa9fa794a8da2d6929b6fb051095090e5503a9cf with gcc 4.6 (ubuntu 12.04) fails :
```
src/screen.cc: In member function ‘void CScreen::execute(std::string)’:
src/screen.cc:229:25: error: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Werror=unused-result]
```

I'm unsure how you'd like to get it fixed.

**Comment by skx** [comment]
Something like we did in the past:

       int result __attribute__((unused));
       result = system( ... )

I think that's reasonably clean.
