### ISSUE TITLE
UI flicks a lot

### ISSUE THREAD

**Issue by trou** [lumail/lumail2#59]
Hi,
I've just started trying lumail2, and on my _slow_ server, the main UI (maildir mode, with the default lumail2.lua) flicks every second. Granted, it's an ssh session inside a tmux inside an ssh session but it's annoying :)

I'll try to find why.

**Comment by skx** [comment]
Suspect the source is the call to `::clear()` in `CScreen::run_main_loop`.

Perhaps remove that, just make sure you call:

      Screen:clear()

When the mode changes, via `change_mode()` in lumail2.lua, or similar.

**Comment by skx** [comment]
Two quick comments.

You might find no changes are required if:

* The caching I added in 4e7990d4f61ed486806be2245b5affeedad512e5 works.
* The `global.timeout` setting is set to 2000, or some other "high" value.
     * This is the timeout between waiting for keys and redrawing.

**Comment by trou** [comment]
Yeah the flicking disappeared.

**Comment by trou** [comment]
It's actually better but "sometimes" it still flicks, I'll leave it open for now.

**Comment by skx** [comment]
I think this is now resolved, via #89.  Which is where I spotted it, but I'll let you confirm :)

**Comment by trou** [comment]
Yes, it looks good :) Thx.

**Comment by skx** [comment]
:)
