### ISSUE TITLE
Our colour handling should be better.

### ISSUE THREAD

**Issue by skx** [lumail/lumail2#61]
We have colour support in our modes, which is awesome, but the setup is buried within the `foo_view()` functions.

Instead we should have a bunch of tables to allow lookups of the form:

     regexp -> colour

This will allow us to do more interesting things, such as colour quoted message-bodies, etc.

**Comment by jugglerchris** [comment]
It'd be nice to have a way of applying colours to only parts of lines.  For example, colour the "From:" and the actual sender differently, highlight your own e-mail address(es) in a Cc: list, URLs within the body, etc.

**Comment by skx** [comment]
Agreed.  I'll tack that onto the end of #62.  I think it should be possible without too much effort.

We just say:

   $[RED]This coloured until the end of the line

vs:

    $[GREEN]green $[RED]red $[YELLOW]yellow ..

The only obvious complication is that checking for string-lengths will be more annoying.

**Comment by jugglerchris** [comment]
The other obvious complication is dealing with strings which include $[RED] to start with, so would need a quoting mechanism too.
Or have the colour out-of-band (separate list of (start,length,colour) pairs).  Can't decide at the moment which I prefer.
