### ISSUE TITLE
Lumail2 uses C++11 regex not supported by older gcc versions (4.6)

### ISSUE THREAD

**Issue by trou** [lumail/lumail2#66]
Running 36b496129bfffe61f9c524fbde54a2385991ac0a on ubuntu 12.04 crashes with:
```
terminate called after throwing an instance of 'std::regex_error'
                                                                   what():  regex_error
                                                                                       Aborted
```
https://stackoverflow.com/questions/8060025/is-this-c11-regex-error-me-or-the-compiler is related.

That's kind of annoying because only gcc 4.9 and later fully support C++11 regexp :(

**Comment by trou** [comment]
#65 seemed to be the same problem, but is now closed.

**Comment by skx** [comment]
That is annoying, indeed.

If the solution suggested there ("using an extra regex_constants parameter to enable a syntax that supports square brackets,") works, then I'd accept that.  If not we'll need to rethink the splitting - the regexp solution is nasty, but it was the sanest I could think of implementing in a hurry.

**Comment by skx** [comment]
OK using the `regexp_constants` option doesn't work.  I'll update to use PCRE, as per:

https://github.com/lumail/experiments/commit/98e8d96693d9074c5bac30c13d0961b4469830df
