### ISSUE TITLE
Required Feature: Derived classes for GUI

### ISSUE THREAD

**Issue by skx** [lumail/lumail2#7]
One of the annoyances of lumail was that the handling for modes contained a lot of duplication.

It seems "obvious" that each mode allows scrolling, so we can create a base-class / interface which will allow:

    void next()
    void prev();
    int selection();
    void selection( int new_value );

We can registered viewers with the CScreen object we're going to write, to allow easy addition of the modes we expect.  And we can store the offsets in the CConfig object we expect.

References:

* #2 
* #1

**Comment by jugglerchris** [comment]
I found I also needed access to the screen object as a global, but I can't now remember why...

**Comment by skx** [comment]
Pretty sure this is done now - we have a small collection of view-modes, each of which has a personal:

* `draw()` method, to draw things.
* `on_idle()` to do stuff in the background.

Both are used in the `demo`-mode.  The former is used in `message`-mode.
