### ISSUE TITLE
Some headers are not decoded or displayed improperly

### ISSUE THREAD

**Issue by trou** [lumail/lumail2#72]
For example: ```"=?UTF-8?Q?=C3=89xxx_xxxx?="``` instead of ```"Éxxx_xxxx"``` or ```Rapha Ml Rigo``` instead of ```Raphaël Rigo``` (encoded as ``` =?ISO-8859-1?Q?Rapha=EBl_Rigo?=```).

I didn't look into it yet.

**Comment by skx** [comment]
Can you try setting the environmental variable `RFC2047` to a true value?

The code in `src/lumail.cc` reads thusly:

       if ( getenv( "RFC2047" ) != NULL)
           g_mime_init(GMIME_ENABLE_RFC2047_WORKAROUNDS);
       else
           g_mime_init (0);

**Comment by trou** [comment]
I forgot about that but I actually have it in my bashrc for lumail1... so it was set.

**Comment by skx** [comment]
:)

Looks like this is why we used the glib UTFstring in the past.  I'd managed to test without it successfully this time round and not spot the problem.  But now I can confirm it.

It might be we can just use UTF on the message-part content, and the message-headers.  Most of the rest of the magic is in Lua-land these days, so we don't have to gradually infect more and more of the core by migrating away from `std::string`.

I'll work on it some tonight, when I'm back from my trip.  But good catch :)

**Comment by skx** [comment]
OK this turns out to be an issue in the drawing-code where I only draw single characters.  The following example Lua works as expected:

      $ cat t.lua 
      f = Message.new( "/home/steve/Maildir/.github.com/cur/1447526519.5007_2.ssh.steve.org.uk:2,S" )
      print( f:header("From") )

The output is:

      $ ~/Repos/lumail/lumail2 $ ./lumail2 --load-file ./t.lua --no-curses
      Raphaël Rigo <notifications@github.com>

So the issue isn't relating to the header parsing, or fetching, but purely the display of the text.

**Comment by trou** [comment]
Hmm now everything is utterly broken (cache rm'd)

**Comment by skx** [comment]
Does this help?

      diff --git a/src/screen.cc b/src/screen.cc
      index a5fe62f..bc71faa 100644
      --- a/src/screen.cc
      +++ b/src/screen.cc
      @@ -1396,13 +1396,15 @@ wchar_t* widen(const char* text)
       {
           int numChars = mbstowcs(NULL, text, 0);
           wchar_t* wideText = (wchar_t *)malloc((numChars + 1) * sizeof(wchar_t));
      -    int convresult = mbstowcs(wideText, text, numChars + 1);
      -
      -    if (convresult != numChars)
      -    {
      -        endwin();
      -        printf("error in mbstowcs()\n");
      -    }
      +    memset(wideText,'\0', numChars+1);
      +    mbstowcs(wideText, text, numChars + 1);
      +
      +    // int convresult = mbstowcs(wideText, text, numChars + 1);
      +    //    if (convresult != numChars)
      +    //    {
      +    //        endwin();
      +    //        printf("error in mbstowcs()\n");
      +    //    }
       
           return wideText;
       }

**Comment by trou** [comment]
No. Still broken.

**Comment by skx** [comment]
Ugh.  OK.  Things look OK to me, in both index and message view, but that function really is horrid.

I suspect we'll need to rework it a little more carefully.

To give me a hint, is it just broken by showing the wrong characters?  Showing rubbish?  Or aborting/segfaulting?

**Comment by trou** [comment]
It's displaying total rubbish.

**Comment by skx** [comment]
OK reworked to stick to `std::string`, and stop trying to mess with encoding, since we proved previously that the value in-string was correct:

* https://github.com/lumail/lumail2/issues/72#issuecomment-156743492

I hope this makes things work for you; certainly it does for me, but then it did previously too.

**NOTE**: This has broken horizontal scrolling.  Perhaps not a big deal.

**Comment by trou** [comment]
The display is now working :) "Raphaël Rigo" is now displayed correctly but ``"=?UTF-8?Q?=C3=89xxx_xxxx?="``` instead of ```"Éxxx_xxxx"``` is still undecoded.

**Comment by skx** [comment]
OK so we're back where we started from:

* UTF-8 is displayed successfully.
* But the message-header is not decoded correctly.

The decoding all happens in `CMessage::headers()`, and that code is identical to what we used in lumail 0.x.  So either something is wrong there, or there is still an issue in storing the decoded value in a `std::string`.

I expect if the issue were the use of `std::string` we'd see "?" displayed, etc.  So I lean towards this being a gmime/decoding issue.  

Does the header show correctly in lumail 0.x?  Or would it be possible to share a broken message with me privately?

**Comment by trou** [comment]
Yeah they work in lumail 0.x. I'll send you the headers by mail.

**Comment by skx** [comment]
Received your mail, thanks a lot.

With lumail 0.x it shows the header correctly __IF__ RFC2047 is set.

If RFC2047 is not set then the header is shown incorrectly.

**Comment by skx** [comment]
That was the hint I needed.  The following patch fixes the issue:

      -    g_mime_init(0);
      +    g_mime_init(GMIME_ENABLE_RFC2047_WORKAROUNDS);

**Comment by skx** [comment]
Will commit shortly,
