### ISSUE TITLE
Issues with navigation.

### ISSUE THREAD

**Issue by skx** [lumail/lumail2#74]
We have a flawed navigation system at the moment, unfortunately.

Assume you have a folder with 50 unread messages, (zero read), then you can enter that folder with:

     index.limit = new

At the start you'll be at the head of the list, so open the first message.  You'll have:

    index.cur = 0
    index.max = 50

Press "`next_message()`", and the current message will be marked as read. You move down, and the variables will be:

     index.cur = 1
     index.max = 49

You can repeat this process about twenty-five times:

    index.cur = 25
    index.max = 35

At that point the `index.cur` is bigger than `index.max` and instead of being at the start of the list you've jumped to the end.  This is because the navigation has become broken.  You've moved forward each time, but you didn't need to.

This requires serious thought to fix, unfortunately.

The specific issue at play is that each time round the loop the current message, having been read, is removed from the `new` list.  Instead we probably need to make a sync function - or similar.

**Comment by jugglerchris** [comment]
FWIW, the way I like this to work is that merely reading messages doesn't change the index - it just marks messages read.  I guess that's what you're talking about with a sync function.

I guess if you go that way (and I think that makes sense) you also want an event for when more mail arrives.  Lua code can then decide whether to update the current displayed index list or not (for example, show a message "3 new messages in mailbox, press $ to sync", or whatever)

**Comment by jugglerchris** [comment]
I guess the way I'd want it to work is that the index.limit only applies when entering the folder, and the list of messages isn't by default updated by magic after that (though you could make it do so from Lua functions).

**Comment by skx** [comment]
Yes that's right.  By sync I mean that we'd update the list of messages, paying attention to the `index.limit`.  But by default the list would stay unchanged even if the messages changed state such that they should no longer be updated.

We could just make the list of current-messages update when either : 

* The maildir changed.
* The index.limit key changed.

(Or via a manual action)

Binding the sorted_messages to use a closure seems like it should make this job almost trivial.  But I'll need to see this evening.

**Comment by skx** [comment]
(We can catch new updates by looking at the `mtime` of the selected Maildir - but I've not yet considered that. )
