### ISSUE TITLE
maildir.prefix not sufficient

### ISSUE THREAD

**Issue by jugglerchris** [lumail/lumail2#76]
I had a quick go at running lumail2 with (nearly) the default config.

Two immediate issues:
* maildir.prefix can only be a single directory (lumail1 supports "foo|bar|baz")
* The default lumail2.lua checks for Directory:is_maildir(def_maildir).  Is that necessary?  I have a non-maildir which contains a bunch of maildirs.

**Comment by skx** [comment]
The first is known, but can be fixed easily.  I'll get that sorted shortly.

The second I think I'm seeing what you mean, but just to confirm if you remove that test does it work as you expect?  If so I'd accept that patch.

**Comment by skx** [comment]
Ahh ignore me - I understand completely.

Will be fixed in a few minutes.
