### ISSUE TITLE
Segfault if the message has no text-part.

### ISSUE THREAD

**Issue by skx** [lumail/lumail2#77]
See for example dmarc-reports supplied by google.

**Comment by trou** [comment]
I just had a segfault with latest git:
```
(gdb) bt
#0  0x00007ffff7bbe4d9 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
#1  0x00007ffff7bb261c in lua_next () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
#2  0x0000000000419328 in CIndexView::get_text (this=<optimized out>) at src/index_view.cc:79
#3  0x000000000041945a in CIndexView::draw (this=0x649a50) at src/index_view.cc:116
#4  0x00000000004284a8 in CScreen::run_main_loop (this=0x64f5b0) at src/screen.cc:199
#5  0x000000000040d9f9 in main (argc=<optimized out>, argv=<optimized out>) at src/lumail2.cc:191
```
I don't know if it's related.

**Comment by skx** [comment]
It could be.  This is my test code:

      local msg = Message.new( "/home/steve/Maildir/.Automated.dmarc/cur/1447840470.29546_1.ssh.steve.org.uk:2,S" )
      local txt = message_view(msg)
      for index,line in ipairs(txt ) do
          print( line )
      end

Launching that program like this:

      $ lumail2 --load-file ./lumail2.lua  --load-file ./t.lu  --no-curses

Gives me the output:

      $[yellow]To: dmarc@steve.org.uk
      $[yellow]From: noreply-dmarc-support@google.com
      $[yellow]Cc: 
      $[yellow]Subject: Report domain: debian-administration.org Submitter: google.com Report-ID: 17107705808172732428
      $[yellow]Date: Wed, 18 Nov 2015 09:54:29 +0000
      
      Failed to find a 'text/xxx' part from the message.

That seems sane - the message doesn't have a text/XXX part, it just contains an attachment and nothing else.    But the client crashes, and it shouldn't.

**Comment by trou** [comment]
So my crash is not related. I'll open another issue.
