### ISSUE TITLE
Multipart message by Apple Mail fails to display correctly

### ISSUE THREAD

**Issue by trou** [lumail/lumail2#79]
I have a mail with:
```
[...]
Content-Type: multipart/mixed; boundary=Apple-Mail-95983C61-6EAF-40BB-9638-7A257EFBFE5A
--Apple-Mail-95983C61-6EAF-40BB-9638-7A257EFBFE5A
Content-Type: text/plain;
   charset=utf-8
Content-Transfer-Encoding: quoted-printable
"mail text here"
[...]
--Apple-Mail-95983C61-6EAF-40BB-9638-7A257EFBFE5A
Content-Type: image/jpeg
[...]
--Apple-Mail-95983C61-6EAF-40BB-9638-7A257EFBFE5A
Content-Type: text/plain;
   charset=utf-8
Content-Transfer-Encoding: quoted-printable
"more mail text here"
```
it only displays "mail text here" when both text/plain parts should be displayed.

**Comment by skx** [comment]
Sounds like you need a patch like so, which updates `message_view()` to show __all__ text/plain parts:


     diff --git a/lumail2.lua b/lumail2.lua
     index 01a018d..cdd89cf 100644
     --- a/lumail2.lua
     +++ b/lumail2.lua
     @@ -1527,8 +1527,6 @@ function message_view( msg )
      
         local found = false
         for i,part in ipairs( parts ) do
     -      if ( found == false ) then
     -
               --
               -- Get the content-type of this part.
               --
          

I'm going to rework attachment mode, such that we can view each part individually, but for the moment I've been assuming we'll continue as before - show the first part only, and if the user wants to customize that then they can, because it is all in the Lua-side now :)

**Comment by trou** [comment]
Sure but sane defaults (as in: "most mails should display as a normal user would expect them to display") are a must :)

**Comment by skx** [comment]
The current default is the same as the previous default; but I'll try showing all parts in my personal installation for the next few days to see if it makes any obvious difference.

If it does look better, globally, we can change the default.

**Comment by trou** [comment]
Well in the mail I was refering, the actual mail written by the sender was split over the different text/plain parts, with a photo inlined. So I was wondering why the mail made no sense until I checked with a different mailer.

**Comment by jugglerchris** [comment]
From a quick test, I don't think the API gives enough information to do the correct thing yet - I don't see the multipart/* containers in msg:parts().

**Comment by skx** [comment]
I have a vague memory there was a previous comment/issue relating to not collapsing the various parts.   Is that what is going on here?

**Comment by jugglerchris** [comment]
Probably this one: https://github.com/lumail/lumail/issues/248

**Comment by skx** [comment]
Good find, thanks.

It seems there are two ways to handle this:

* export a tree - such that CMessageParts can contain children.
* Export a list from CMessage, but don't join the parts, and return each child which is multipart-mixed separately.

The latter is easier, and I think I can implement it.

**Comment by jugglerchris** [comment]
Aha, I can now see the multipart parts.  I can't see the parent/child relationship yet, though.

**Comment by skx** [comment]
Yeah this is a compromise - the parts are retrieved as a list, not a tree.

I expect it'll take a bit of work as it'll change the way that CMessageParts are built/used.

**Comment by skx** [comment]
This should be broken into two distinct bugs:

* Handle CMessageParts as a tree, not a list.
* Display *all* text/plain, or text/html parts by default.  Not just the first.

Though I remain unconvinced that the second is a sensible default it shouldn't be difficult to add either locally or globally.

**Comment by skx** [comment]
Closing this as it is now being tracked in two dedicated issues.
