### ISSUE TITLE
Better Lua debuggability

### ISSUE THREAD

**Issue by jugglerchris** [lumail/lumail2#84]
Hi,
At the moment, if there's an error in a Lua function (eg index_view()), it is silently ignored.  I think it'd be a big usability improvement to at least print the error message from lua_pcall somewhere, and ideally a stack trace.
A single error I guess could go into the panel, and a stack trace either in a text view or a log file.
I think at least some of the above could be implemented using just an "on_error" callback (which itself, of course, would be harder to debug).
Chris

**Comment by skx** [comment]
Good idea.

I'll implement `on_error( msg )` which will by default append to the panel.

**Comment by jugglerchris** [comment]
Thanks, that's a good improvement!
