### ISSUE TITLE
Can't select maildir immediately after starting

### ISSUE THREAD

**Issue by jugglerchris** [lumail/lumail2#86]
When starting lumail2, and pressing "Enter" to select the first maildir, nothing happens. Moving up or down fixes it.  I think this is because the "maildir.current" config item starts out as `nil`, confusing the select() function.

**Comment by skx** [comment]
Good observation.

Does this fix it?

       function select()
          local mode = Config:get("global.mode")
      -   local cur  = Config:get(mode .. ".current")
      +   local cur  = Config:get_with_default(mode .. ".current", 0)

**Comment by jugglerchris** [comment]
Yep, that fixes it.
