### ISSUE TITLE
No German Umlauts in mail texts?

### ISSUE THREAD

**Issue by RquasiR** [lumail/lumail2#97]
Apparantly mail texts are not presented in utf-8. 
I'm missing German umlauts and the sharp s.

**Comment by skx** [comment]
I thought I'd got to the bottom of this previously.  Could you let me know:

* Do you see UTF-8 in the index-view (i.e. sender/from details)?
* Do you see UTF-8 in the message view?  (I guess not)
* If you open a message that should show UTF-8 can you please:
      * Press `A` to open attachment view.
      * Move up/down to select the appropriate part.
      * Press `ENTER` to open the part via `less`.
      * Tell me whether it displays UTF-8?

The latter test will help us rule out whether it is the message that is not being parsed/returned correctly, or whether the screen display is broken.

**Comment by RquasiR** [comment]
Good morning, Steve. Please wait until lower middle of afternoon.
I'm awaiting old friends right now.

Besides the UTF-8 problem I then will report on an occasional 
memory access error, too.

**Comment by skx** [comment]
No rush from my side - have a nice day!

**Comment by RquasiR** [comment]
Thank you Steve. I'm back now.

> * Do you see UTF-8 in the index-view (i.e. sender/from details)?
Yes, all those lines seem to be ok!

> * Do you see UTF-8 in the message view?  (I guess not)

It's very strange: At first glance I found using lumail2 only message bodies with correct 
German umlauts and the French "é"! Finally I succeeded in looking up a message body 
with spaces instead of umlauts. Then I invoked this same message by mutt and found 
it ok (with umlauts)! Strange that.

> * If you open a message that should show UTF-8 can you please:
>       * Press `A` to open attachment view.
>       * Move up/down to select the appropriate part.
>       * Press `ENTER` to open the part via `less`.
>       * Tell me whether it displays UTF-8?

No, it doesn't. Here is a part of this message:

zun<E4>chst einmal w<FC>nsche ich Ihnen ein gutes Neues Jahr 2014. Leider kommt meine Antwort auf Ihre Anfrage etwas versp<E4>tet, aber zum Jahreswechsel sind wir mit Abschlussarbeiten usw. ziemlich besch<E4>ftigt. Ich kann Ihnen aber mitteilen, dass ich den Heiratseintrag von Benjamin Kammerer und Anna Stockburger geb. Frick gefunden habe. Da es sich bei dem Eintrag um Archivgut handelt, kann ich Ihnen eine begl. Kopie des Eintrages zukommen lassen. Im Eintrag sind Hinweise zu zwei Kindern aus dieser Ehe enthalten, jedoch kein Vermerk <FC>ber den Tod von Herrn Kammerer. Bitte <FC>berweisen Sie die Geb<FC>hr in H<F6>he von 5,00 Euro auf eines der nachfolgend genannten Konten; ich werde Ihnen die Kopie dann zuschicken.

<E4> should be "ä"
<FC> should be "ü" and so forth.

**Comment by skx** [comment]
One last test - if you pull down the most recent git changes and launch lumail2, then press `L` for lua-mode do you see UTF in the top-two lines?

I'm suspecting that because you see the correct values in the message-index that means that the terminal is setup correctly, and that the bug here is something relating to the display of the message, which means that the message-parsing is failing.  If you __do__ see the correct output after pressing `L` this will confirm that suspicion.

**Comment by RquasiR** [comment]
Compilation failed after having downloaded the newest lumail2 (7cc6)

sam@nan:~/lumail2$ make
g++  -std=c++0x -Wall -Werror -I/usr/include/lua5.2   -I/usr/include/ncursesw  -DLUMAIL_VERSION="\"7cc6\"" -D_LARGEFILE64_SOURCE -pthread -I/usr/include/gmime-2.6 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -O2 -c src/message_lua.cc -o obj.release/message_lua.o
g++  -std=c++0x -Wall -Werror -I/usr/include/lua5.2   -I/usr/include/ncursesw  -DLUMAIL_VERSION="\"7cc6\"" -D_LARGEFILE64_SOURCE -pthread -I/usr/include/gmime-2.6 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -O2 -c src/mime_lua.cc -o obj.release/mime_lua.o
In file included from src/mime_lua.cc:27:0:
src/mime.h:22:19: fatal error: magic.h: Datei oder Verzeichnis nicht gefunden
 #include <magic.h>
                   ^
compilation terminated.
Makefile:97: recipe for target 'obj.release/mime_lua.o' failed
make: *** [obj.release/mime_lua.o] Error 1

"Datei oder Verzeichnis nicht gefunden" means "File or folder not found",

**Comment by skx** [comment]
This should fix it assuming you're on Debian/Ubuntu:

     apt-get install libmagic-dev

For CentOS/Fedora/etc you'll have to find the appropriate package name.

It's a new build-dependency, which made sure I added to the documentation!

**Comment by RquasiR** [comment]
Compilation is ok again, but after invoking
 
./lumail2 --load-file ./lumail2.lua

I'm getting:

          This is 'maildir' mode.

          No maildirs are currently visible.

**Comment by skx** [comment]
OK I've just pushed a new update to `lumail2.lua` which should resolve that.

**Comment by RquasiR** [comment]
Yes, I'm seeing UTF-8 coded letters:

This is Lumail2 version f1d5

This line is for UTF-8 testing «ÜßÄ$€»‹ÅåÄäÖö›

**Comment by skx** [comment]
Perfect.  That proves that the display-code is correct, and the error is in the handling of the message-content.

My last update of the night has added support for character-set conversion, which might resolve this problem.  I can't tell.

If you do one more git-update, such that you're on version `f1d5` you can then add to the end of `lumail2.lua` the line:

     Config:set("global.iconv", 1)

Then relaunch the client.  I'm wary of enabling this by default for the moment, but if it fixes the problem for you then we'll do that tomorrow, or so.

**Comment by RquasiR** [comment]
I added this line at the end of lumail2.lua after git and make, but after relaunching lumail2 and searching this certain mail again: Nothing had changed.
Spaces where instead of umlauts.

**Comment by skx** [comment]
That's frustrating, but thank you for trying.

I think the only way to proceed now is if you can zip up a broken mail and forward to me directly, so I can see if I can reproduce the problem - obviously only if the mails aren't too sensitive.

If you can zip & attach to me at steve@steve.org.uk I'll have a look at it ASAP.

**Comment by RquasiR** [comment]
Good morning, Steve. Yes, I shall send you this mail. Please wait a couple of minutes.

**Comment by RquasiR** [comment]
Just an idea: Microsoft coding of german umlauts?

**Comment by skx** [comment]
Thanks to @RquasiR  for sharing a sample email with me privately, the sample provided is encoded as:

    Content-Type: text/plain; charset="iso-8859-1"

The specific issue is that my attempt last night to convert the mails to UTF-8 was failing.  I think I can get this sorted early this evening, and will update then.  Once done it'll be time for a new release.
